version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+mysqlconnector://sarbaseuser:password@db/sarbaseapp

  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sarbaseapp
      MYSQL_USER: sarbaseuser
      MYSQL_PASSWORD: password

volumes:
  db-data:
